In [1]:
import polars as pl
import duckdb
import plotly
import os

print("Polars :", pl.__version__)
print("DuckDB :", duckdb.__version__)
print("Plotly :", plotly.__version__)

Polars : 1.44.2
DuckDB : 1.5.6
Plotly : 7.1.0

In [2]:
DATA_PATH = "../data/raw/indonesia_palm_oil_v1_2_5.csv"

print("Dataset:", DATA_PATH)
print("File ditemukan:", os.path.exists(DATA_PATH))

Dataset: ../data/raw/indonesia_palm_oil_v1_2_5.csv
File ditemukan: True

In [3]:
df = pl.scan_csv(DATA_PATH)

print("Dataset berhasil dibaca menggunakan Polars Lazy API")

Dataset berhasil dibaca menggunakan Polars Lazy API

In [4]:
schema = df.collect_schema()

print("Jumlah kolom:", len(schema))
print("\nSchema:")
print(schema)

Jumlah kolom: 34

Schema:
Schema({'year': Int64, 'country_of_production': String, 'product_type': String, 'forest_500_palm_oil': String, 'zero_deforestation_indonesia_palm_oil': String, 'province_of_production': String, 'kabupaten_of_production': String, 'mill': String, 'mill_trase_id': String, 'mill_group': String, 'refinery': String, 'refinery_trase_id': String, 'refinery_group': String, 'exporter': String, 'exporter_group': String, 'port_of_export': String, 'importer': String, 'importer_group': String, 'country_of_first_import': String, 'economic_bloc': String, 'province_of_production_trase_id': String, 'kabupaten_of_production_trase_id': String, 'country_of_production_trase_id': String, 'country_of_first_import_trase_id': String, 'palm_oil_deforestation_10_year_total_exposure': String, 'palm_oil_deforestation_annual_exposure': String, 'total_emission_exposure': String, 'net_emission_luc_exposure': String, 'emission_subsidence_exposure': String, 'gross_emission_luc_exposure': String, 'emissions_fire_on_peat_exposure': String, 'volume': Float64, 'oil_palm_ha': String, 'fob': String})

In [5]:
row_count = df.select(
    pl.len().alias("jumlah_baris")
).collect()

print(row_count)

shape: (1, 1)
┌──────────────┐
│ jumlah_baris │
│ ---          │
│ u32          │
╞══════════════╡
│ 1694907      │
└──────────────┘

In [6]:
df.head(5).collect()

shape: (5, 34)
┌──────┬──────────────┬──────────────┬─────────────┬───┬─────────────┬────────┬─────────────┬──────┐
│ year ┆ country_of_p ┆ product_type ┆ forest_500_ ┆ … ┆ emissions_f ┆ volume ┆ oil_palm_ha ┆ fob  │
│ ---  ┆ roduction    ┆ ---          ┆ palm_oil    ┆   ┆ ire_on_peat ┆ ---    ┆ ---         ┆ ---  │
│ i64  ┆ ---          ┆ str          ┆ ---         ┆   ┆ _exposur…   ┆ f64    ┆ str         ┆ str  │
│      ┆ str          ┆              ┆ str         ┆   ┆ ---         ┆        ┆             ┆      │
│      ┆              ┆              ┆             ┆   ┆ str         ┆        ┆             ┆      │
╞══════╪══════════════╪══════════════╪═════════════╪═══╪═════════════╪════════╪═════════════╪══════╡
│ 2013 ┆ INDONESIA    ┆ PALM OIL     ┆ NOT         ┆ … ┆ null        ┆ 22.8   ┆ null        ┆ null │
│      ┆              ┆              ┆ ASSESSED    ┆   ┆             ┆        ┆             ┆      │
│ 2013 ┆ INDONESIA    ┆ PALM OIL     ┆ NOT         ┆ … ┆ null        ┆ 3000.0 ┆ null        ┆ null │
│      ┆              ┆              ┆ ASSESSED    ┆   ┆             ┆        ┆             ┆      │
│ 2013 ┆ INDONESIA    ┆ PALM OIL     ┆ NOT         ┆ … ┆ null        ┆ 1000.0 ┆ null        ┆ null │
│      ┆              ┆              ┆ ASSESSED    ┆   ┆             ┆        ┆             ┆      │
│ 2013 ┆ INDONESIA    ┆ PALM OIL     ┆ NOT         ┆ … ┆ null        ┆ 1000.0 ┆ null        ┆ null │
│      ┆              ┆              ┆ ASSESSED    ┆   ┆             ┆        ┆             ┆      │
│ 2013 ┆ INDONESIA    ┆ PALM OIL     ┆ NOT         ┆ … ┆ null        ┆ 500.0  ┆ null        ┆ null │
│      ┆              ┆              ┆ ASSESSED    ┆   ┆             ┆        ┆             ┆      │
└──────┴──────────────┴──────────────┴─────────────┴───┴─────────────┴────────┴─────────────┴──────┘

In [7]:
schema = df.collect_schema()

for nama_kolom, tipe_data in schema.items():
    print(f"{nama_kolom:<40} {tipe_data}")

year                                     Int64
country_of_production                    String
product_type                             String
forest_500_palm_oil                      String
zero_deforestation_indonesia_palm_oil    String
province_of_production                   String
kabupaten_of_production                  String
mill                                     String
mill_trase_id                            String
mill_group                               String
refinery                                 String
refinery_trase_id                        String
refinery_group                           String
exporter                                 String
exporter_group                           String
port_of_export                           String
importer                                 String
importer_group                           String
country_of_first_import                  String
economic_bloc                            String
province_of_production_trase_id          String
kabupaten_of_production_trase_id         String
country_of_production_trase_id           String
country_of_first_import_trase_id         String
palm_oil_deforestation_10_year_total_exposure String
palm_oil_deforestation_annual_exposure   String
total_emission_exposure                  String
net_emission_luc_exposure                String
emission_subsidence_exposure             String
gross_emission_luc_exposure              String
emissions_fire_on_peat_exposure          String
volume                                   Float64
oil_palm_ha                              String
fob                                      String

In [8]:
from pathlib import Path

file_path = Path(DATA_PATH)

size_bytes = file_path.stat().st_size
size_mb = size_bytes / (1024 ** 2)
size_gb = size_bytes / (1024 ** 3)

print(f"Ukuran file : {size_mb:.2f} MB")
print(f"Ukuran file : {size_gb:.2f} GB")

Ukuran file : 721.83 MB
Ukuran file : 0.70 GB

In [9]:
missing = df.select([
    pl.col(col).null_count().alias(col)
    for col in df.collect_schema().names()
]).collect()

missing

shape: (1, 34)
┌──────┬──────────────┬─────────────┬─────────────┬───┬─────────────┬────────┬─────────────┬───────┐
│ year ┆ country_of_p ┆ product_typ ┆ forest_500_ ┆ … ┆ emissions_f ┆ volume ┆ oil_palm_ha ┆ fob   │
│ ---  ┆ roduction    ┆ e           ┆ palm_oil    ┆   ┆ ire_on_peat ┆ ---    ┆ ---         ┆ ---   │
│ u32  ┆ ---          ┆ ---         ┆ ---         ┆   ┆ _exposur…   ┆ u32    ┆ u32         ┆ u32   │
│      ┆ u32          ┆ u32         ┆ u32         ┆   ┆ ---         ┆        ┆             ┆       │
│      ┆              ┆             ┆             ┆   ┆ u32         ┆        ┆             ┆       │
╞══════╪══════════════╪═════════════╪═════════════╪═══╪═════════════╪════════╪═════════════╪═══════╡
│ 0    ┆ 0            ┆ 0           ┆ 0           ┆ … ┆ 1025290     ┆ 0      ┆ 10233       ┆ 10957 │
└──────┴──────────────┴─────────────┴─────────────┴───┴─────────────┴────────┴─────────────┴───────┘

In [10]:
total_rows = df.select(
    pl.len()
).collect().item()

unique_rows = df.unique().select(
    pl.len()
).collect().item()

duplicate_rows = total_rows - unique_rows

print("Total baris      :", total_rows)
print("Baris unik       :", unique_rows)
print("Duplikasi        :", duplicate_rows)

Total baris      : 1694907
Baris unik       : 1694907
Duplikasi        : 0

In [11]:
missing_profile = (
    df
    .select([
        pl.col(col).null_count().alias(col)
        for col in df.collect_schema().names()
    ])
    .collect()
    .transpose(
        include_header=True,
        header_name="column",
        column_names=["missing_count"]
    )
    .with_columns(
        (
            pl.col("missing_count") / total_rows * 100
        ).round(2).alias("missing_percentage")
    )
    .sort("missing_count", descending=True)
)

missing_profile

shape: (34, 3)
┌─────────────────────────────────┬───────────────┬────────────────────┐
│ column                          ┆ missing_count ┆ missing_percentage │
│ ---                             ┆ ---           ┆ ---                │
│ str                             ┆ u32           ┆ f64                │
╞═════════════════════════════════╪═══════════════╪════════════════════╡
│ total_emission_exposure         ┆ 1025290       ┆ 60.49              │
│ net_emission_luc_exposure       ┆ 1025290       ┆ 60.49              │
│ emission_subsidence_exposure    ┆ 1025290       ┆ 60.49              │
│ gross_emission_luc_exposure     ┆ 1025290       ┆ 60.49              │
│ emissions_fire_on_peat_exposur… ┆ 1025290       ┆ 60.49              │
│ …                               ┆ …             ┆ …                  │
│ province_of_production_trase_i… ┆ 0             ┆ 0.0                │
│ kabupaten_of_production_trase_… ┆ 0             ┆ 0.0                │
│ country_of_production_trase_id  ┆ 0             ┆ 0.0                │
│ country_of_first_import_trase_… ┆ 0             ┆ 0.0                │
│ volume                          ┆ 0             ┆ 0.0                │
└─────────────────────────────────┴───────────────┴────────────────────┘

In [12]:
unique_rows = (
    df
    .unique()
    .select(pl.len().alias("unique_rows"))
    .collect()
    .item()
)

duplicate_rows = total_rows - unique_rows

print("Total baris   :", total_rows)
print("Baris unik    :", unique_rows)
print("Baris duplikat:", duplicate_rows)

Total baris   : 1694907
Baris unik    : 1694907
Baris duplikat: 0

In [13]:
numeric_columns = [
    name
    for name, dtype in df.collect_schema().items()
    if dtype.is_numeric()
]

print("Kolom numerik:")
for col in numeric_columns:
    print("-", col)

Kolom numerik:
- year
- volume

In [15]:
numeric_summary = df.select(numeric_columns).describe()

numeric_summary

shape: (9, 3)
┌────────────┬─────────────┬──────────────┐
│ statistic  ┆ year        ┆ volume       │
│ ---        ┆ ---         ┆ ---          │
│ str        ┆ f64         ┆ f64          │
╞════════════╪═════════════╪══════════════╡
│ count      ┆ 1.694907e6  ┆ 1.694907e6   │
│ null_count ┆ 0.0         ┆ 0.0          │
│ mean       ┆ 2020.051917 ┆ 226.346597   │
│ std        ┆ 1.35405     ┆ 15280.810851 │
│ min        ┆ 2013.0      ┆ 5.0414e-11   │
│ 25%        ┆ 2019.0      ┆ 0.152118     │
│ 50%        ┆ 2020.0      ┆ 2.12001      │
│ 75%        ┆ 2021.0      ┆ 21.216855    │
│ max        ┆ 2022.0      ┆ 1.1605e7     │
└────────────┴─────────────┴──────────────┘

In [16]:
# Mengecek tipe data seluruh kolom

schema_df = pl.DataFrame({
    "column": df.collect_schema().names(),
    "dtype": [str(dtype) for dtype in df.collect_schema().values()]
})

schema_df

shape: (34, 2)
┌─────────────────────────────────┬─────────┐
│ column                          ┆ dtype   │
│ ---                             ┆ ---     │
│ str                             ┆ str     │
╞═════════════════════════════════╪═════════╡
│ year                            ┆ Int64   │
│ country_of_production           ┆ String  │
│ product_type                    ┆ String  │
│ forest_500_palm_oil             ┆ String  │
│ zero_deforestation_indonesia_p… ┆ String  │
│ …                               ┆ …       │
│ gross_emission_luc_exposure     ┆ String  │
│ emissions_fire_on_peat_exposur… ┆ String  │
│ volume                          ┆ Float64 │
│ oil_palm_ha                     ┆ String  │
│ fob                             ┆ String  │
└─────────────────────────────────┴─────────┘

In [17]:
check_columns = [
    "year",
    "volume",
    "oil_palm_ha",
    "fob"
]

schema_df.filter(
    pl.col("column").is_in(check_columns)
)

shape: (4, 2)
┌─────────────┬─────────┐
│ column      ┆ dtype   │
│ ---         ┆ ---     │
│ str         ┆ str     │
╞═════════════╪═════════╡
│ year        ┆ Int64   │
│ volume      ┆ Float64 │
│ oil_palm_ha ┆ String  │
│ fob         ┆ String  │
└─────────────┴─────────┘